
### Add Contact Test Case
POST http://localhost:3000/api/contacts/add
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "ahmed",
    "friendUsername": "dhmi"
}

### Remove Contact Test Case
POST http://localhost:3000/api/contacts/remove
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "ahmed",
    "friendUsername": "dhmi"
}

### Accept Contact Test Case
POST http://localhost:3000/api/contacts/accept
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "dhmi",
    "friendUsername": "ahmed"
}


### Add Contact Test Case
POST http://localhost:3000/api/contacts/add
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "ahmed",
    "friendUsername": "wld"
}

### Remove Contact Test Case
POST http://localhost:3000/api/contacts/remove
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "ahmed",
    "friendUsername": "wld"
}

### Accept Contact Test Case
POST http://localhost:3000/api/contacts/accept
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "wld",
    "friendUsername": "ahmed"
}