### Signup Test Case
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "dhmi",
    "email": "dhmi@example.com",
    "password": "123",
    "phone": "1234567890",
    "country": "USA",
    "phoneExtension": "+1",
    "picture": "profile.jpg",
    "department": "Engineering",
    "city": "New York",
    "company": "Tech Corp",
    "descruption": "A new user",
    "firstName": "John",
    "lastName": "Doe"
}

### Login Test Case
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "dhmi@example.com",
    "password": "123"
}


