
### Add Contact Test Case
POST http://localhost:3000/api/contacts/add
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "john_doe",
    "friendUsername": "jane_doe"
}

### Remove Contact Test Case
POST http://localhost:3000/api/contacts/remove
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "john_doe",
    "friendUsername": "jane_doe"
}

### Accept Contact Test Case
POST http://localhost:3000/api/contacts/accept
Content-Type: application/json
Authorization: Bearer <JWT_TOKEN>

{
    "username": "jane_doe",
    "friendUsername": "john_doe"
}
